### ISSUE TITLE
Version issue with windows plugin

### ISSUE THREAD

**Issue by Ze8h** [katursis/Pawn.Regex#4]
#define PAWNREGEX_INCLUDE_VERSION 112

It would not work with windows plugin version as 112  but it would work as `#define PAWNREGEX_INCLUDE_VERSION 111`
I have tried building the latest files in both windows and linux but no effect in windows while its working with linux.

And this goes opposite for linux. If its 112 then its fine and if its 111 then it dosent.

**Comment by katursis** [comment]
https://github.com/urShadow/Pawn.Regex/releases/tag/1.1.2
