### ISSUE TITLE
Word boundary (\b)

### ISSUE THREAD

**Issue by v4yne1** [katursis/Pawn.Regex#7]
This is my code:

```
public OnPlayerText(playerid, text[])
{
    new Regex:r = Regex_New("\b(word1|word2|word3)\b", REGEX_ICASE),
        RegexMatch:m,
        startpos, pos;

    if(Regex_Search(text, r, m, pos, startpos))
    {
        SendClientMessage(playerid, 0xF154ACFF, "Detected");
        return 0;
    }

    Regex_Delete(r);
    return 1;
}
```

This is how it should work:

https://i.imgur.com/wtbb9Wi.png

When I type word1 or word2 or word3 ingame, nothing happens. But, when I remove '\b' from regex pattern it works, but not the way I want. Without using '\b' it will capture word even if it's mixed within another word.
Like this:

https://i.imgur.com/1LdPxtl.png

**Comment by katursis** [comment]
Regex_New("**\\**\b(word1|word2|word3)**\\**\b", REGEX_ICASE)

**Comment by v4yne1** [comment]
> Regex_New("**\**\b(word1|word2|word3)**\**\b", REGEX_ICASE)

Thanks, sir :+1:
